### ISSUE TITLE
does anyone have the xtreme 2 v1.6.0?

### ISSUE THREAD

**Issue by M4lw4reT3sts** [Dnstje/JBL-Charge-3-firmware#3]
This version had the best sound imo and i have 2.3.0 and I would like to roll it back somehow

**Comment by r3d5ky** [comment]
Here you go, try it :)
[Xtreme2_v1.6.0.zip](https://github.com/ZuwaiiVR/JBL-Charge-3-firmware/files/6319417/Xtreme2_v1.6.0.zip)
[Xtreme2_v1.9.0.zip](https://github.com/ZuwaiiVR/JBL-Charge-3-firmware/files/6319419/Xtreme2_v1.9.0.zip)
[Xtreme2_v2.0.0.zip](https://github.com/ZuwaiiVR/JBL-Charge-3-firmware/files/6319420/Xtreme2_v2.0.0.zip)

**Comment by M4lw4reT3sts** [comment]
OH MY GOD THANK YOUUU
