### ISSUE TITLE
 Any patches for these speakers?

### ISSUE THREAD

**Issue by Technowithoutthat** [Dnstje/JBL-Charge-3-firmware#5]
I'm new to this github page and got here through a link and I'm hoping it's still active and open for questions
I have seen some files that include firmware versions for specific speakers

These files are all .dfu files and I found them for the following speakers

Flip 3
Flip 4
Charge 3
Pulse 3
Boombox

But that's cool and all but what was I'm actually looking for are specific versions for friends that wish to
update to specific versions.

They're looking for

Flip 5 - 0.3.0 (important)
Xtreme 2 - 2.4.0 (important)
Charge 4 - 3.0.0 The owner of the charge 4 said he had this version but it's not very important to him.

If anyone can find any of these versions I would be very thankful
I don't have notifications on or anything so I only get here to check here every once in a while
but still any reply would be appreciated.

**Comment by M4lw4reT3sts** [comment]
Charge 4 3.0.0
https://mega.nz/file/nDBB2Q6Z#8E6rhMPgZvkRYKrTHKr68ecoizBkykduRSD2o8kObrg

Xtreme 2 2.7.0 & 2.0.0
https://mega.nz/file/eHBFRabQ#eSE1UC3ZXGZ9Tx0TsBADgyG6x59eoWmusGz6GIHQr6Y

Nothing for the Flip 5 :(

**Comment by Technowithoutthat** [comment]
.
