### ISSUE TITLE
Does someone have Charge 4 2.7.0 Firmware?

### ISSUE THREAD

**Issue by danielniccoli** [Dnstje/JBL-Charge-3-firmware#6]
I hope to find the Firmware 2.4.0 for the Charge 4. Anybody has it?

**Comment by M4lw4reT3sts** [comment]
No but there is version 2.4.0 and 3.0.0

**Comment by danielniccoli** [comment]
Oh, you're right. I updated the post.

Do you have a link to 2.4.0? I inspected the meta information from the decompiled Android app and unfortunately, all I could find is a link to the current version 3.0.0.

**Comment by M4lw4reT3sts** [comment]
https://github.com/pembem22/jbl-firmware Only the CSR one has older versions.
